name: LookMaxx
targets:
  LookMaxx:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
        excludes:
          - "project.yml"
          - "*.xcodeproj"
          - "*.xcworkspace"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.LookMaxx
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: ""
